### ISSUE TITLE
The path to the lombok.jar file is hard-coded

### ISSUE THREAD

**Issue by tristan957** [microsoft/vscode-lombok#2]
I am a person who uses VSCode on multiple platforms, so the location of my .vscode extension varies whether I am on Windows, Mac, and Linux. Is it possible to make the path platform agnostic, possible a `${configFolder}`.

https://github.com/Microsoft/vscode/issues/2809

**Comment by GabrielBB** [comment]
Hi , @tristan957. Are you syncing your user settings between your different platforms? Because the Lombok jar path in inserted in your user.settings not in your workspace.settings. If you install the Lombok extension in the visual studio code installed in every platform it recognize the platform you’re working in. For example, i use it on my work Pc and my personal Mac and I don’t have problems with it since I just install the extension on both. Just like you would do with any other extension

**Comment by GabrielBB** [comment]
Thanks for notifying it. I didn’t know about people doing setting syncing until now, so I was not aware of this issue. I hope they solve the linked issue

**Comment by testforstephen** [comment]
In the latest version 1.1.0, the lombok agent in this extension is removed because RedHat Java extension has built-in lombok support by default. This lombok extension no longer injects lombok agent to 'java.jdt.ls.vmargs'.
